### ISSUE TITLE
package.json contains UNLICENSED flag but I believe it should be SPDX-License-Identifier: Apache-2.0

### ISSUE THREAD

**Issue by jeff-luszcz** [danfuzz/lactoserv#165]
**Describe the bug**
The package.json files in the various src modules contain a package.json file with UNLICENSED flag in the id field.

A short summary of the problem.

**To reproduce**

Steps to reproduce the problem:

Examine each package.json file (e.g. https://github.com/danfuzz/lactoserv/blob/main/src/app-config/package.json )
You will see

  "license": "UNLICENSED",

**Expected behavior**

expect to see the SPDX license identifier for Apache 2.0

"license": "SPDX-License-Identifier: Apache-2.0",

**Actual behavior**

package.json contains UNLICENSED flag

**Environment**

n/a

**Additional context**

n/a

**Comment by danfuzz** [comment]
Thanks for spotting this!
